//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/czero/de_fastline_cz.html
gfx/env/morningdewbk.tga
gfx/env/morningdewdn.tga
gfx/env/morningdewft.tga
gfx/env/morningdewlf.tga
gfx/env/morningdewrt.tga
gfx/env/morningdewup.tga
decals.wad
models/props/plant_potted.mdl
models/props/rails_subway.mdl
models/props/tree_japan_maple_orange.mdl
models/props/lamp_portable_standup.mdl
models/props/wires_still.mdl
models/props/scaffold.mdl
models/props/scaffold_short.mdl
models/props/trash.mdl
sound/ambience/fastline/fastline_station3.wav
sound/ambience/fastline/fastline_turnreject.wav
sound/ambience/fastline/fastline_station2.wav
czde_fastline.wad
maps/de_fastline_cz.bsp
