//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/de_stadium_cz.html
czritual_standard.wad
overviews/de_stadium_cz.txt
overviews/de_stadium_cz.bmp
models/props/bush_shrub_little.mdl
models/props/bush_japan_fern_01.mdl
models/props/trash_trashcan.mdl
models/props/cashregister.mdl
models/props/shower.mdl
models/props/bathroom_urinal.mdl
models/props/soccer_bag.mdl
models/props/bush_shrubv01.mdl
models/props/soda_fountain.mdl
models/props/popcornmachine.mdl
models/props/bush_japan_bush01.mdl
czde_stadium_pi.wad
maps/de_stadium_cz.txt
decals.wad
models/props/chair_cafe.mdl
models/props/table_cafe.mdl
gfx/env/londonbk.tga
gfx/env/londondn.tga
gfx/env/londonft.tga
gfx/env/londonlf.tga
gfx/env/londonrt.tga
gfx/env/londonup.tga
maps/de_stadium_cz.bsp
