//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/valve/dutch_subway.html
sound/ambience/waterfall1.wav
gfx/env/city_nightbk.tga
gfx/env/city_nightdn.tga
gfx/env/city_nightft.tga
gfx/env/city_nightlf.tga
gfx/env/city_nightrt.tga
gfx/env/city_nightup.tga
sprites/laserbeam.spr
sprites/dutch/du_tele2.spr
sound/dutch/train/metrostops.wav
sound/dutch/train/stationhall.wav
sound/dutch/train/metrovertrek.wav
maps/dutch_subway.bsp
