//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/valve/dutch_wintercold_v2.html
sprites/blue_teleport.spr
sound/ambience/rotormachine.wav
sound/ambience/dronemachine1.wav
sound/ambience/dronemachine2.wav
gfx/env/snowcliff_bk.tga
gfx/env/snowcliff_dn.tga
gfx/env/snowcliff_ft.tga
gfx/env/snowcliff_lf.tga
gfx/env/snowcliff_rt.tga
gfx/env/snowcliff_up.tga
sprites/sexysmoke.spr
maps/dutch_wintercold_v2.bsp
